DROP TABLE IF EXISTS searches;

CREATE TABLE searches (
  counter INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  location TEXT NOT NULL,
  radius REAL NOT NULL,
  nsrc INTEGER NOT NULL,
  filename TEXT UNIQUE NOT NULL
);
